---
- name: Restart php-fpm
  ansible.builtin.systemd:
    name: 'php{{ php_version }}-fpm'
    state: restarted

- name: Reload nginx
  ansible.builtin.systemd:
    name: 'nginx'
    state: reloaded

